//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmvLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmvLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;CAKeys&gt;&lt;CAKeyElement&gt;&lt;RID&gt;A000000004&lt;/RID&gt;&lt;Index&gt;00&lt;/Index&gt;&lt;CAKey&gt;9E15214212F6308ACA78B80BD986AC287516846C8D548A9ED0A42E7D997C902C3E122D1B9DC30995F4E25C75DD7EE0A0CE293B8CC02B977278EF256D761194924764942FE714FA02E4D57F282BA3B2B62C9E38EF6517823F2CA831BDDF6D363D&lt;/CAKey&gt;&lt;Exponent&gt;03&lt;/Exponent&gt;&lt;SHA1Hash&gt;&lt;/SHA1Hash&gt;&lt;Expiry&gt;&lt;/Expiry&gt;&lt;/CAKeyElement&gt;&lt;CAKeyElement&gt;&lt;RID&gt;A000000003&lt;/RID&gt;&lt;Index&gt;01&lt;/Index&gt;&lt;CAKey&gt;C696034213D7D8546984579D1D0F0EA519CFF8DEFFC429354CF3A871A6F7183F1228DA5C7470C055387100CB935A712C4E2864DF5D64BA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cakeys {
            get {
                return ResourceManager.GetString("cakeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5F 2A,00 00 00 00 00,Transaction Currency Code,09 75
        ///5F 2A,A0 00 00 06 15,Transaction Currency Code,09 78
        ///5F 36,00 00 00 00 00,Transaction Currency Exponent,02
        ///71,00 00 00 00 00,Issuer Script Template 1,
        ///72,00 00 00 00 00,Issuer Script Template 2,
        ///81,00 00 00 00 00,Amount Authorised Binary,00 00 00 11
        ///81,A0 00 00 00 04,Profile ID,01
        ///83,00 00 00 00 00,Command Template,00 00 00 00
        ///86,00 00 00 00 00,Issuer Script Command,
        ///89,00 00 00 00 00,Authorisation Code,
        ///8A,00 00 00 00 00,Authorisation Response Code,30 30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string terminal_data_elements {
            get {
                return ResourceManager.GetString("terminal_data_elements", resourceCulture);
            }
        }
    }
}
